### PR TITLE
Day 2 first project 

### PR DESCRIPTION
**Pull request by quavo19**

### CODE REVIEW

**Review by anagudelogu — CHANGES_REQUESTED** [review]
Hi @quavo19, I'm Andres, your reviewer.

Great job setting up your first Microverse project! 🍾 🎆 
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
✅ Great linters setup. 💯 
✅ Descriptive commit messages. 👍🏼 
✅ GitHub flow correctly followed. 💯 

## Required Changes ♻️
- [x] Kindly use the [Microverse's Readme template](https://github.com/microverseinc/readme-template) 🗒️ and customize it with your project information, changing the relevant fields. At the moment you're missing important information about your project, such as the name, and a `Getting started` section which describes the steps on how others can get a local copy of your project up and running. 🛠️ 

- [x] You did a great job with your commit messages! 💯  However, you are missing a pull request summary, which is part of the professional documentation. Please, update this summary to describe briefly what you did in this Milestone 🛠️  

image

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by quavo19** [comment]
this is my day2 project in microverse, under HTML and CSS

**Comment by quavo19** [comment]
### Day2 Project in microverse
- installed Linters and other packages

- made CSS and HTML files

-  committed the README.md file and resolved conflicts

**Review by Santiago220991 — APPROVED** [review]
Hi @quavo19, 
I'm Santiago your reviewer for this PR. :wave: :wave: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
:heavy_check_mark: Applied changes suggested by the last reviewer.
:heavy_check_mark: Followed GitHub flow.
:heavy_check_mark: No linter errors.

## Optional suggestions
[OPTIONAL] Kindly remember that your commit message should be written in the imperative tense. :+1: :smiley: :smiley: . Please apply this in future projects.

[OPTIONAL] Please make sure to give a meaningful name to your feature branch. It helps to know quickly what changes you applied to your project. :eyes: :eyes: Please apply this in future projects.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
